layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # youtube: your_username
  # vk: your_username

topics:
  - name: Security
    web_url: https://github.com/topics/security
    image_url: https://s15-us2.startpage.com/cgi-bin/serveimage?url=https%3A%2F%2Fwww.split.io%2Fwp-content%2Fthemes%2Fsplit%2Fassets%2Fimages%2Ftrust%2Fsecurity%2Ficon-infrastructure-security.png%3Fb8211a29&sp=eb1dcee47f89af41c28cdabd52347e7e

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

theme: jekyll-theme-cayman